/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as MlopsRouteImport } from './routes/mlops'
import { Route as MlInsightsRouteImport } from './routes/ml-insights'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces.$traceId'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents.$incidentId'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const MlopsRoute = MlopsRouteImport.update({
  id: '/mlops',
  path: '/mlops',
  getParentRoute: () => rootRouteImport,
} as any)
const MlInsightsRoute = MlInsightsRouteImport.update({
  id: '/ml-insights',
  path: '/ml-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => TracesRoute,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => IncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/audit': typeof AuditRoute
  '/deployments': typeof DeploymentsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/ml-insights': typeof MlInsightsRoute
  '/mlops': typeof MlopsRoute
  '/organizations': typeof OrganizationsRoute
  '/queues': typeof QueuesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRouteWithChildren
  '/workers': typeof WorkersRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/audit': typeof AuditRoute
  '/deployments': typeof DeploymentsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/ml-insights': typeof MlInsightsRoute
  '/mlops': typeof MlopsRoute
  '/organizations': typeof OrganizationsRoute
  '/queues': typeof QueuesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRouteWithChildren
  '/workers': typeof WorkersRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/api': typeof ApiRoute
  '/audit': typeof AuditRoute
  '/deployments': typeof DeploymentsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/ml-insights': typeof MlInsightsRoute
  '/mlops': typeof MlopsRoute
  '/organizations': typeof OrganizationsRoute
  '/queues': typeof QueuesRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/topology': typeof TopologyRoute
  '/traces': typeof TracesRouteWithChildren
  '/workers': typeof WorkersRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/api'
    | '/audit'
    | '/deployments'
    | '/events'
    | '/forgot-password'
    | '/incidents'
    | '/login'
    | '/logs'
    | '/ml-insights'
    | '/mlops'
    | '/organizations'
    | '/queues'
    | '/services'
    | '/settings'
    | '/signup'
    | '/topology'
    | '/traces'
    | '/workers'
    | '/incidents/$incidentId'
    | '/traces/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/api'
    | '/audit'
    | '/deployments'
    | '/events'
    | '/forgot-password'
    | '/incidents'
    | '/login'
    | '/logs'
    | '/ml-insights'
    | '/mlops'
    | '/organizations'
    | '/queues'
    | '/services'
    | '/settings'
    | '/signup'
    | '/topology'
    | '/traces'
    | '/workers'
    | '/incidents/$incidentId'
    | '/traces/$traceId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/api'
    | '/audit'
    | '/deployments'
    | '/events'
    | '/forgot-password'
    | '/incidents'
    | '/login'
    | '/logs'
    | '/ml-insights'
    | '/mlops'
    | '/organizations'
    | '/queues'
    | '/services'
    | '/settings'
    | '/signup'
    | '/topology'
    | '/traces'
    | '/workers'
    | '/incidents/$incidentId'
    | '/traces/$traceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiRoute: typeof ApiRoute
  AuditRoute: typeof AuditRoute
  DeploymentsRoute: typeof DeploymentsRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IncidentsRoute: typeof IncidentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MlInsightsRoute: typeof MlInsightsRoute
  MlopsRoute: typeof MlopsRoute
  OrganizationsRoute: typeof OrganizationsRoute
  QueuesRoute: typeof QueuesRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TopologyRoute: typeof TopologyRoute
  TracesRoute: typeof TracesRouteWithChildren
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mlops': {
      id: '/mlops'
      path: '/mlops'
      fullPath: '/mlops'
      preLoaderRoute: typeof MlopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-insights': {
      id: '/ml-insights'
      path: '/ml-insights'
      fullPath: '/ml-insights'
      preLoaderRoute: typeof MlInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof TracesRoute
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof IncidentsRoute
    }
  }
}

interface IncidentsRouteChildren {
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

interface TracesRouteChildren {
  TracesTraceIdRoute: typeof TracesTraceIdRoute
}

const TracesRouteChildren: TracesRouteChildren = {
  TracesTraceIdRoute: TracesTraceIdRoute,
}

const TracesRouteWithChildren =
  TracesRoute._addFileChildren(TracesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiRoute: ApiRoute,
  AuditRoute: AuditRoute,
  DeploymentsRoute: DeploymentsRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IncidentsRoute: IncidentsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MlInsightsRoute: MlInsightsRoute,
  MlopsRoute: MlopsRoute,
  OrganizationsRoute: OrganizationsRoute,
  QueuesRoute: QueuesRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TopologyRoute: TopologyRoute,
  TracesRoute: TracesRouteWithChildren,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
