CREATE TYPE public.event_status AS ENUM ('success', 'failed', 'retrying', 'queued', 'processing');
CREATE TYPE public.severity_level AS ENUM ('info', 'warning', 'error', 'critical');
CREATE TYPE public.log_level AS ENUM ('debug', 'info', 'warn', 'error', 'critical');
CREATE TYPE public.worker_status AS ENUM ('online', 'offline', 'degraded');
CREATE TYPE public.queue_status AS ENUM ('healthy', 'degraded', 'backlogged');
CREATE TYPE public.service_status AS ENUM ('healthy', 'degraded', 'down');
CREATE TYPE public.incident_status AS ENUM ('investigating', 'identified', 'monitoring', 'resolved');
CREATE TYPE public.incident_severity AS ENUM ('sev1', 'sev2', 'sev3', 'sev4');
CREATE TYPE public.deployment_status AS ENUM ('succeeded', 'failed', 'rolled_back', 'in_progress');
CREATE TYPE public.deployment_env AS ENUM ('prod', 'staging', 'dev');
CREATE TYPE public.ml_model_status AS ENUM ('serving', 'shadow', 'deprecated');
CREATE TYPE public.ml_insight_type AS ENUM ('anomaly', 'prediction', 'summary');
CREATE TYPE public.slo_status AS ENUM ('healthy', 'at_risk', 'breached');
CREATE TYPE public.sli_type AS ENUM ('availability', 'latency', 'error_rate', 'throughput');
CREATE TYPE public.topology_kind AS ENUM ('gateway', 'service', 'queue', 'worker', 'db', 'ml');
CREATE TYPE public.notification_kind AS ENUM ('alert', 'incident', 'deploy', 'queue', 'worker');
CREATE TYPE public.api_key_status AS ENUM ('active', 'revoked');
CREATE TYPE public.member_status AS ENUM ('active', 'invited', 'suspended');
CREATE TYPE public.member_role_pulse AS ENUM ('admin', 'engineer', 'viewer', 'analyst');
CREATE TYPE public.plan_type AS ENUM ('free', 'pro', 'enterprise');
CREATE TYPE public.pulse_environment AS ENUM ('prod', 'staging', 'dev', 'preview');
CREATE TYPE public.span_kind AS ENUM ('server', 'client', 'internal', 'producer', 'consumer');
CREATE TYPE public.span_status AS ENUM ('ok', 'error');
CREATE TYPE public.trace_status AS ENUM ('ok', 'error', 'degraded');
CREATE TYPE public.http_method AS ENUM ('GET', 'POST', 'PUT', 'DELETE', 'PATCH');
